#!/usr/bin/env python3
"""
Tier 3, Task 3.3: Cosmological Constant Spectral Density on D₄ Lattice

Computes the vacuum energy spectral density integral over the D₄ Brillouin
zone and investigates the geometric suppression mechanism that yields
ρ_Λ/ρ_P = α⁵⁷/(4π).

The manuscript (§V.5) claims:
  ρ_Λ = (1/2) ∫_BZ d⁴k/(2π)⁴ Σ_b ℏω_b(k) × f_suppression(k)

where ω_b(k) is the phonon dispersion (computed in d4_phonon_spectrum.py)
and f_suppression is a phase-averaging suppression function involving:
  - 19 hidden shear modes
  - 3 triality sectors
  - Zone-boundary zero at R = (π,π,π,π)

The claimed α⁵⁷ scaling with 57 = 3×19 arises from the dissipation of
each shear mode through each triality sector.

This script tests whether the spectral structure supports this scaling.
"""
import numpy as np
import sys
from scipy import integrate


# =============================================================================
# D₄ lattice phonon spectrum (from d4_phonon_spectrum.py)
# =============================================================================

def d4_root_vectors():
    """Generate all 24 root vectors of D₄."""
    roots = []
    for i in range(4):
        for j in range(i + 1, 4):
            for si in [1, -1]:
                for sj in [1, -1]:
                    v = np.zeros(4)
                    v[i] = si
                    v[j] = sj
                    roots.append(v)
    return np.array(roots)


def dynamical_matrix(k, roots, J=1.0):
    """Compute 4×4 dynamical matrix at wavevector k."""
    D = np.zeros((4, 4))
    for delta in roots:
        norm_sq = np.dot(delta, delta)
        outer = np.outer(delta, delta) / norm_sq
        phase = 1 - np.cos(np.dot(k, delta))
        D += J * outer * phase
    return D


def phonon_eigenvalues(k, roots, J=1.0):
    """Compute the 4 phonon eigenvalues ω²(k)."""
    D = dynamical_matrix(k, roots, J)
    eigs = np.linalg.eigvalsh(D)
    return np.maximum(eigs, 0)  # ensure non-negative


# =============================================================================
# Vacuum energy spectral density
# =============================================================================

def bare_vacuum_energy(roots, n_samples=100000, J=1.0, seed=42):
    """
    Compute the bare (unsuppressed) vacuum energy:
      E_vac = (1/2) ∫_BZ d⁴k/(2π)⁴ Σ_b ω_b(k)

    This is the full zero-point energy per unit cell (in lattice units).
    """
    np.random.seed(seed)
    bz_vol = (2 * np.pi)**4  # BZ volume (lattice units with a₀=1)

    total_omega = 0.0
    batch_size = min(n_samples, 5000)
    processed = 0

    while processed < n_samples:
        this_batch = min(batch_size, n_samples - processed)
        k_batch = np.random.uniform(-np.pi, np.pi, size=(this_batch, 4))

        for i in range(this_batch):
            eigs = phonon_eigenvalues(k_batch[i], roots, J)
            total_omega += np.sum(np.sqrt(eigs))

        processed += this_batch

    avg_omega = total_omega / n_samples
    E_vac = 0.5 * avg_omega  # (1/2)⟨Σ_b ω_b⟩ per BZ integration point

    return E_vac, avg_omega


def triality_suppression_factor(k, roots):
    """
    Compute the triality phase-averaging suppression factor.

    The D₄ lattice has S₃ triality symmetry that permutes the three
    8-dimensional irreducible representations (8_v, 8_s, 8_c) of SO(8).

    The triality action on the wavevector space is generated by the
    outer automorphisms of D₄, which permute the three end nodes of
    the Dynkin diagram. For a given k, the three triality-related
    wavevectors k, σ(k), σ²(k) have the SAME phonon spectrum (by
    symmetry) but different PHASES.

    The physical vacuum energy is the coherent sum over triality sectors:
      f_triality(k) = |1 + e^{iφ₁(k)} + e^{iφ₂(k)}|² / 9

    where φ₁, φ₂ are the relative phases of the triality-rotated modes.

    For generic k: destructive interference gives f ~ 1/3
    For k on high-symmetry lines: f can be 0 or 1
    At R = (π,π,π,π): f = 0 (perfect cancellation)
    """
    # D₄ triality acts on the root system by permuting the three
    # 'legs' of the Dynkin diagram. In terms of the standard basis
    # e₁±e₂, e₃±e₄ (Lie algebra roots), the triality exchanges:
    # e₁+e₂ ↔ e₁-e₂ ↔ e₃+e₄ (roughly)

    # For the 4D displacement vectors, triality acts as a
    # permutation matrix P₃ of order 3.
    # Simple model: P₃ acts on the 4 eigenvalues by cyclic permutation
    # of 3 of them (keeping 1 fixed — the breathing mode).

    # Phase from triality rotation
    eigs = phonon_eigenvalues(k, roots)
    omega = np.sqrt(eigs)

    if np.sum(omega) < 1e-15:
        return 0.0  # zero mode → zero contribution

    # Relative phases from the triality action
    # The triality maps k → T₁(k), T₂(k) where T₁, T₂ are the
    # non-trivial elements of S₃ acting on the BZ.
    # For D₄ in standard coordinates:
    # T₁: (k₁,k₂,k₃,k₄) → (½(k₁+k₂+k₃+k₄), ½(k₁+k₂-k₃-k₄),
    #                          ½(k₁-k₂+k₃-k₄), ½(k₁-k₂-k₃+k₄))
    # This is the triality matrix from the D₄ outer automorphism.

    # D₄ triality acts on the root system via the outer automorphisms
    # of the D₄ Dynkin diagram (S₃ permuting the three 'legs').
    # In the standard basis, one generator of the Z₃ cyclic triality
    # is represented by the Hadamard-like matrix below, which maps
    # (e₁±e₂) ↔ ½(e₁±e₂±e₃±e₄) while preserving the root lattice.
    T1 = 0.5 * np.array([
        [1,  1,  1,  1],
        [1,  1, -1, -1],
        [1, -1,  1, -1],
        [1, -1, -1,  1]
    ])
    T2 = T1 @ T1  # T₂ = T₁²

    k1 = T1 @ k
    k2 = T2 @ k

    # Eigenvalues at triality-related points
    eigs1 = phonon_eigenvalues(k1, roots)
    eigs2 = phonon_eigenvalues(k2, roots)
    omega1 = np.sqrt(eigs1)
    omega2 = np.sqrt(eigs2)

    # Total energy at each triality point
    E0 = np.sum(omega)
    E1 = np.sum(omega1)
    E2 = np.sum(omega2)

    # Phase difference from dispersion
    # φ_i(k) = Σ_b [ω_b(T_i·k) - ω_b(k)] × a₀/c (dimensionless)
    phi1 = np.sum(omega1 - omega)
    phi2 = np.sum(omega2 - omega)

    # Coherent sum with phase factors
    amplitude = 1 + np.exp(1j * phi1) + np.exp(1j * phi2)
    f_triality = np.abs(amplitude)**2 / 9.0

    return f_triality


def shear_mode_suppression(k, roots, alpha=1.0/137.036):
    """
    Compute the shear mode suppression factor.

    The 24 DOF per D₄ site decompose as:
      1 breathing + 4 translational + 19 shear

    The 19 shear modes do not couple to the resonance condition and
    act as dissipative channels. Each shear mode transmits a fraction
    α of its energy per interaction (α = fine-structure constant = the
    vacuum impedance).

    The suppression from N_s shear modes across N_t triality sectors is:
      f_shear = α^(N_s × N_t) = α^(19×3) = α^57
    """
    N_shear = 19
    N_triality = 3

    # The suppression is k-independent (it's a property of the lattice
    # structure, not the wavevector). This is the key claim of §V.5.
    return alpha**(N_shear * N_triality)


def compute_spectral_density(n_samples=50000, J=1.0, seed=42):
    """
    Compute the full vacuum energy spectral density with suppression.

    Returns:
      E_bare:      unsuppressed vacuum energy
      E_triality:  with triality phase averaging
      E_shear:     with shear mode suppression
      E_full:      with both suppressions
    """
    roots = d4_root_vectors()
    alpha = 1.0 / 137.036

    np.random.seed(seed)

    E_bare_sum = 0.0
    E_triality_sum = 0.0
    n_valid = 0

    batch_size = min(n_samples, 2000)
    processed = 0

    while processed < n_samples:
        this_batch = min(batch_size, n_samples - processed)
        k_batch = np.random.uniform(-np.pi, np.pi, size=(this_batch, 4))

        for i in range(this_batch):
            k = k_batch[i]
            eigs = phonon_eigenvalues(k, roots, J)
            omega_sum = np.sum(np.sqrt(eigs))
            E_bare_sum += omega_sum

            f_tri = triality_suppression_factor(k, roots)
            E_triality_sum += omega_sum * f_tri
            n_valid += 1

        processed += this_batch

    E_bare = 0.5 * E_bare_sum / n_samples
    E_triality = 0.5 * E_triality_sum / n_valid

    # Shear mode suppression is a global factor
    f_shear_global = alpha**(19 * 3)  # = α⁵⁷
    E_shear = E_bare * f_shear_global
    E_full = E_triality * f_shear_global

    return E_bare, E_triality, E_shear, E_full, f_shear_global


def main():
    print("=" * 76)
    print("COSMOLOGICAL CONSTANT SPECTRAL DENSITY ON D₄ LATTICE (v83.0 Session 4)")
    print("=" * 76)
    print()

    alpha = 1.0 / 137.036
    roots = d4_root_vectors()

    # ===== Part 1: Bare vacuum energy =====
    print("Part 1: Bare Vacuum Energy (No Suppression)")
    print("-" * 60)
    n_samples = 50000
    E_vac, avg_omega = bare_vacuum_energy(roots, n_samples=n_samples)
    print(f"  Monte Carlo samples: {n_samples}")
    print(f"  ⟨Σ_b ω_b(k)⟩ = {avg_omega:.6f} (lattice units)")
    print(f"  E_vac = ½ × {avg_omega:.6f} = {E_vac:.6f} (lattice units)")
    print()

    # In Planck units: E_vac_Planck = E_vac × (J × ℏ²/a₀²) / ρ_P
    # Since we work in lattice units with J=1, the bare vacuum energy
    # density is ρ_bare ~ E_vac × ρ_P (order unity in Planck units)
    print(f"  In Planck units: ρ_bare/ρ_P ~ {E_vac:.4f} (order unity ✅)")
    print(f"  This confirms the vacuum catastrophe: bare ρ ~ ρ_P")
    print()

    # ===== Part 2: Triality phase averaging =====
    print("Part 2: Triality Phase Averaging")
    print("-" * 60)
    print()

    # Test at specific k-points
    test_points = {
        'Γ': np.array([0.01, 0.0, 0.0, 0.0]),  # near Γ (avoid exact 0)
        'X': np.array([np.pi, 0, 0, 0]),
        'M': np.array([np.pi, np.pi, 0, 0]),
        'R': np.array([np.pi, np.pi, np.pi, np.pi]),
        'Generic': np.array([1.0, 0.5, 0.3, 0.7]),
    }

    for name, k in test_points.items():
        f_tri = triality_suppression_factor(k, roots)
        eigs = phonon_eigenvalues(k, roots)
        omega_sum = np.sum(np.sqrt(eigs))
        print(f"  {name:>8s}: ω_sum = {omega_sum:.4f}, f_triality = {f_tri:.6f}")

    print()
    print("  Key observation: triality suppression is O(1) — it provides")
    print("  modest averaging (factor ~1/3) but NOT the 10¹²³ suppression.")
    print("  The dominant suppression must come from the shear modes.")
    print()

    # ===== Part 3: Shear mode suppression =====
    print("Part 3: Shear Mode Geometric Suppression")
    print("-" * 60)
    print()

    N_s = 19  # shear modes
    N_t = 3   # triality sectors
    gamma = N_s * N_t  # = 57

    alpha_57 = alpha**gamma
    alpha_57_over_4pi = alpha_57 / (4 * np.pi)

    print(f"  Number of shear modes: {N_s} (= 24 - 4 - 1)")
    print(f"  Number of triality sectors: {N_t}")
    print(f"  Total suppression exponent: γ = {N_s} × {N_t} = {gamma}")
    print()
    print(f"  α⁵⁷ = (1/137.036)⁵⁷ = {alpha_57:.4e}")
    print(f"  α⁵⁷/(4π) = {alpha_57_over_4pi:.4e}")
    print()

    # Compare with observed value
    rho_Lambda_over_rho_P_obs = 1.26e-123  # Planck 2018
    rho_Lambda_predicted = alpha_57_over_4pi

    print(f"  Predicted: ρ_Λ/ρ_P = α⁵⁷/(4π) = {rho_Lambda_predicted:.4e}")
    print(f"  Observed:  ρ_Λ/ρ_P = {rho_Lambda_over_rho_P_obs:.4e}")
    agreement = rho_Lambda_predicted / rho_Lambda_over_rho_P_obs
    print(f"  Ratio predicted/observed = {agreement:.4f}")
    print(f"  Agreement: {abs(1-agreement)*100:.1f}%")
    print()

    # ===== Part 4: Spectral structure analysis =====
    print("Part 4: Spectral Structure of Vacuum Energy")
    print("-" * 60)
    print()
    print("  The phonon spectrum contributes to ρ_Λ through the integral:")
    print("    ρ_Λ = (1/2) ∫_BZ d⁴k/(2π)⁴ Σ_b ω_b(k) × f_supp(k)")
    print()
    print("  The key question: does f_supp(k) emerge from the lattice dynamics")
    print("  or is α⁵⁷/(4π) imposed by hand?")
    print()

    # Compute the spectral weight function
    print("  Spectral weight distribution:")
    n_bins = 20
    omega_bins = np.linspace(0, 8, n_bins + 1)
    counts = np.zeros(n_bins)
    weighted = np.zeros(n_bins)

    np.random.seed(42)
    n_spec = 20000
    for _ in range(n_spec):
        k = np.random.uniform(-np.pi, np.pi, 4)
        eigs = phonon_eigenvalues(k, roots)
        for e in eigs:
            omega = np.sqrt(e)
            idx = np.searchsorted(omega_bins[1:], omega)
            if idx < n_bins:
                counts[idx] += 1
                weighted[idx] += omega

    print(f"  {'ω range':>12s}  {'N(ω)':>8s}  {'Σω':>10s}  {'fraction':>8s}")
    total_weight = np.sum(weighted)
    for i in range(n_bins):
        if counts[i] > 0:
            frac = weighted[i] / total_weight if total_weight > 0 else 0
            print(f"  [{omega_bins[i]:4.1f}, {omega_bins[i+1]:4.1f}]  "
                  f"{counts[i]:8.0f}  {weighted[i]:10.1f}  {frac:8.4f}")

    print()

    # ===== Part 5: Full computation =====
    print("Part 5: Full Spectral Density Computation")
    print("-" * 60)
    print()

    E_bare, E_triality, E_shear, E_full, f_shear = compute_spectral_density(
        n_samples=20000
    )

    print(f"  E_bare (no suppression):         {E_bare:.6f} × ρ_P")
    print(f"  E_triality (phase averaging):    {E_triality:.6f} × ρ_P")
    print(f"  E_shear (α⁵⁷ suppression):       {E_bare * f_shear:.4e} × ρ_P")
    print(f"  E_full (triality + shear):        {E_full:.4e} × ρ_P")
    print()
    print(f"  Triality suppression factor:      {E_triality/E_bare:.4f} (modest)")
    print(f"  Shear mode suppression:           α⁵⁷ = {f_shear:.4e}")
    print(f"  Combined suppression:             {E_full/E_bare:.4e}")
    print()

    # Compare with target
    target = alpha_57_over_4pi
    E_full_normalized = E_full / (4 * np.pi)  # Account for angular normalization
    print(f"  Full result / (4π):               {E_full_normalized:.4e}")
    print(f"  Target α⁵⁷/(4π):                 {target:.4e}")
    print()

    # ===== Part 6: Honest assessment =====
    print("Part 6: Honest Assessment")
    print("-" * 60)
    print()
    print("  WHAT WORKS:")
    print("  ✅ The phonon spectrum is explicitly computed (d4_phonon_spectrum.py)")
    print("  ✅ The zone-boundary zero at R provides a natural IR regulator")
    print("  ✅ The shear mode counting 19 = 24 - 4 - 1 is algebraically exact")
    print("  ✅ The triality sector count 3 is a topological invariant of D₄")
    print(f"  ✅ The product α⁵⁷/(4π) = {alpha_57_over_4pi:.4e} matches")
    print(f"     observation ({rho_Lambda_over_rho_P_obs:.4e}) to {abs(1-agreement)*100:.1f}%")
    print()
    print("  WHAT DOESN'T WORK (honest gaps):")
    print("  ❌ The suppression f_supp = α⁵⁷ is POSTULATED, not derived from")
    print("     the BZ integral. The spectral density integral without the")
    print("     suppression gives ρ ~ ρ_P (vacuum catastrophe persists).")
    print("  ❌ The physical mechanism 'each shear mode dissipates fraction α'")
    print("     is a HEURISTIC, not a first-principles calculation.")
    print("  ❌ The 1/(4π) normalization factor is assigned to angular averaging")
    print("     but not derived from the actual angular integral.")
    print("  ❌ The triality phase averaging gives O(1) suppression, not the")
    print("     claimed perfect cancellation at zone boundaries.")
    print()
    print("  CLASSIFICATION: The α⁵⁷ scaling is")
    print("    - Numerically correct (matches observation to ~1%)")
    print("    - Structurally motivated (19 shear modes × 3 triality sectors)")
    print("    - NOT yet derived from first principles")
    print("    - Grade: B- (counting argument correct, mechanism heuristic)")
    print()

    return 0


if __name__ == "__main__":
    sys.exit(main())
