name = "IHMFramework"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["IHMFramework"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "IHMFramework"
globs = ["IHMFramework", "IHMFramework.Basic", "IHMFramework.V2Basic", "IHMFramework.V2Problems", "IHMFramework.FiveDesign", "IHMFramework.Circularity", "IHMFramework.LiebRobinson", "IHMFramework.MeasureUniqueness", "IHMFramework.D4Uniqueness", "IHMFramework.Goldstone", "IHMFramework.GaugeInvariance"]
